// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
)

type AuthUser struct {
	InstanceID               uuid.NullUUID         `json:"instance_id"`
	ID                       uuid.UUID             `json:"id"`
	Aud                      sql.NullString        `json:"aud"`
	Role                     sql.NullString        `json:"role"`
	Email                    sql.NullString        `json:"email"`
	EncryptedPassword        sql.NullString        `json:"encrypted_password"`
	EmailConfirmedAt         sql.NullTime          `json:"email_confirmed_at"`
	InvitedAt                sql.NullTime          `json:"invited_at"`
	ConfirmationToken        sql.NullString        `json:"confirmation_token"`
	ConfirmationSentAt       sql.NullTime          `json:"confirmation_sent_at"`
	RecoveryToken            sql.NullString        `json:"recovery_token"`
	RecoverySentAt           sql.NullTime          `json:"recovery_sent_at"`
	EmailChangeTokenNew      sql.NullString        `json:"email_change_token_new"`
	EmailChange              sql.NullString        `json:"email_change"`
	EmailChangeSentAt        sql.NullTime          `json:"email_change_sent_at"`
	LastSignInAt             sql.NullTime          `json:"last_sign_in_at"`
	RawAppMetaData           pqtype.NullRawMessage `json:"raw_app_meta_data"`
	RawUserMetaData          pqtype.NullRawMessage `json:"raw_user_meta_data"`
	IsSuperAdmin             sql.NullBool          `json:"is_super_admin"`
	CreatedAt                sql.NullTime          `json:"created_at"`
	UpdatedAt                sql.NullTime          `json:"updated_at"`
	Phone                    sql.NullString        `json:"phone"`
	PhoneConfirmedAt         sql.NullTime          `json:"phone_confirmed_at"`
	PhoneChange              sql.NullString        `json:"phone_change"`
	PhoneChangeToken         sql.NullString        `json:"phone_change_token"`
	PhoneChangeSentAt        sql.NullTime          `json:"phone_change_sent_at"`
	ConfirmedAt              sql.NullTime          `json:"confirmed_at"`
	EmailChangeTokenCurrent  sql.NullString        `json:"email_change_token_current"`
	EmailChangeConfirmStatus sql.NullInt16         `json:"email_change_confirm_status"`
	BannedUntil              sql.NullTime          `json:"banned_until"`
	ReauthenticationToken    sql.NullString        `json:"reauthentication_token"`
	ReauthenticationSentAt   sql.NullTime          `json:"reauthentication_sent_at"`
	IsSsoUser                bool                  `json:"is_sso_user"`
	DeletedAt                sql.NullTime          `json:"deleted_at"`
}

type Game struct {
	ID           uuid.UUID      `json:"id"`
	Fen          sql.NullString `json:"fen"`
	History      sql.NullString `json:"history"`
	Completed    bool           `json:"completed"`
	DateStarted  time.Time      `json:"date_started"`
	DateFinished sql.NullTime   `json:"date_finished"`
	CurrentState string         `json:"current_state"`
}

type PlayerGame struct {
	UserID uuid.UUID `json:"user_id"`
	GameID uuid.UUID `json:"game_id"`
	Color  string    `json:"color"`
}
